[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake==3.21",
    # MLIR build depends.
    "ninja",
    "numpy==1.23.1",
    "pybind11==2.10.1",
    "PyYAML",
    "pip",
    "requests"
]
build-backend = "setuptools.build_meta"